### ISSUE TITLE
`package.json` import maps not resolved correctly when it points to a directory under `outDir`

### ISSUE THREAD

**Issue by SuperchupuDev** [privatenumber/tsx#329] opened 2023-09-30 15:08 UTC
### Problem

When [`resolvePackageJsonImports`](https://www.typescriptlang.org/tsconfig#resolvePackageJsonImports) is enabled in tsconfig.json, and they point to somewhere inside the `outDir` directory, TypeScript will resolve the package import as the same file but inside the `rootDir` directory.

However tsx does not, it resolves to the original package import directory, making this behavior inconsistent with typescript

This makes something like `"imports": { "#*": "./dist/*" }` work as expected under TypeScript (point to `./src/*`), but makes tsx point to `./dist/*`

### Expected behavior

tsx having behavior consistent with TypeScript and resolving to the corresponding file inside `rootDir`

### Minimal reproduction URL

https://stackblitz.com/edit/node-9muqn2?file=REPRO-INSTRUCTIONS.md&view=editor

### Version

v3.13.0

### Node.js version

v20.7.0

### Package manager

pnpm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by SuperchupuDev** [comment] 2023-09-30 15:10
looks like this is a duplicate of #3296, however it got closed without resolving

**Comment by privatenumber** [comment] 2023-10-01 00:51
This would be a feature request since TS released this after tsx, and this was simply not implemented.

As it says in the closing comment, #296 was closed as a duplicate, not because it's resolved; the referenced issue is still open.

I think this is a separate issue though. This ticket is about TypeScript customizing Node's import/export map logic to consider `outDir`, whereas #296 is about simply implementing Node's import/export map logic.

**Comment by privatenumber** [comment] 2024-06-11 21:43
I looked into this and the expected behavior doesn't seem to be correct: TypeScript is _not_ mapping imports to a missing outDir directory back to the source:
![Screenshot 2024-06-12 at 6 41 14 AM](https://github.com/privatenumber/tsx/assets/1075694/524d8659-48a5-4274-88d6-4ec7409222ef)

It just so happens to work post compilation because it creates the files, but TypeScript is not intentionally doing that.

Closing as expected behavior.

**Closed by privatenumber** 2024-06-11 21:43 UTC
Labels: enhancement, resolver

**Comment by SuperchupuDev** [comment] 2024-06-11 23:34
typescript solves the imports at the type level though, automatically pointing to the correct types

**Comment by gaastonsr** [comment] 2024-08-29 00:52
Someone just reported the same thing with a reproduction url #603 and I can confirm I'm facing the same issue.

**Comment by privatenumber** [comment] 2024-08-29 01:34
Please don't comment on closed issues. Especially if you're going to reference one that's open.

And also, if you're going to make a claim, please back it. There's an explanation with a screenshot above demonstrating why this particular issue is expected.
