### ISSUE TITLE
ESM files should be able to import TS files using `.js` import specifier

### ISSUE THREAD

**Issue by AurelienRibon** [privatenumber/tsx#490] opened 2024-03-07 13:56 UTC
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://stackblitz.com/edit/node-ueeyeu

### Version

4.7.1

### Node.js version

21.6.2

### Package manager

npm

### Operating system

macOS

### Problem & Expected behavior

TypeScript documentation makes it very clear that TSC will never rewrite an import specifier [1] [2]. Thus, it is the responsibility of users to use the proper import specifiers in their import statements. As a consequence, when using ESM instead of CommonJS, typescript files must be imported using `import './foo.js'` (esm) instead of `import './foo'` (cjs) or `import './foo.ts'` (unofficial).

`tsc` compiles those imports without problem, vscode understands them and provides intellisense, but `tsx` fails to load them unfortunately. Note that vscode even autocompletes those `.js` specifiers for importing TS files, and never proposes the `.ts` extension.

For `tsx` to work, I need to replace the `.js` in the import specifier with `.ts`, which is wrong.

[1] https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#type-in-packagejson-and-new-extensions
[2] https://dev.to/ayc0/typescript-50-new-mode-bundler-esm-1jic

// Extract from typescriptlang.org
<img width="953" alt="image" src="https://github.com/privatenumber/tsx/assets/1777005/0499f072-7fc9-4196-9283-bab1b5206e71">

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by AurelienRibon** [comment] 2024-03-07 13:57
Note that one can circumvent this issue by writing a custom Node loader, to override TSX.
This custom code tries to resolve all specifiers to a `.ts` file before fallbacking to the default tsx resolution.

```js
import { load, resolve as resolveTsx } from 'tsx';

export { load };

export async function resolve(specifier, ctx, defaultResolve) {
  // JS imports can point to JS or TS files, so we need to check both.
  if (specifier.endsWith('.js')) {
    const specifierTs = specifier.replace(/\.js$/, '') + '.ts';
    try {
      return await resolveTsx(specifierTs, ctx, defaultResolve);
    } catch (err) {
      return resolveTsx(specifier, ctx, defaultResolve);
    }
  }

  // Fallback for other files (like module imports, json, etc.)
  return resolveTsx(specifier, ctx, defaultResolve);
}
```

**Comment by privatenumber** [comment] 2024-03-07 14:15
Closing as a duplicate of https://github.com/privatenumber/tsx/issues/135

FYI the issue is misplaced—there's already resolution logic to resolve `.ts` files via `.js`.

The problem is tsx currently doesn't add TypeScript enhancements to `.js` files even if `allowJs` is enabled. (Similar to how tsc doesn't compile `.js` files unless `allowJs` is enabled.) Once `allowJs` is supported, this will be fixed.

Also, I don't use upvotes as a metric to prioritize issues, but I do know some projects use it to measure community interest. I think it's a little spammy and in-genuine that 5 of your co-workers upvoted your issue within 10 min of posting it.

**Closed by privatenumber** 2024-03-07 14:15 UTC
Labels: bug, pending triage
