### ISSUE TITLE
`tsImport` results are various from whether `type: "module"` is set or not

### ISSUE THREAD

**Issue by ntnyq** [privatenumber/tsx#611] opened 2024-07-13 23:08 UTC
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/ntnyq-dev/repro-tsx-esm-api

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment] 2024-07-14 01:26
Duplicate of https://github.com/privatenumber/tsx/issues/427

The underlying issue is in Node

**Closed** 2024-07-14 01:28 UTC
Labels: bug, pending triage
