### ISSUE TITLE
lodash named exports fails to import with `"type": "module"` in `package.json`

### ISSUE THREAD

**Issue by segevfiner** [privatenumber/tsx#361] opened 2023-10-31 12:07 UTC
### Problem

With `"type": "module"` in the `package.json`, and and named import of a function from `lodash` (Pure CJS, not statically analyzable by Node.js). You will get an error:
```
> start
> tsx index.ts

(node:10) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/projects/node-bixnfe/index.ts:1
var __defProp=Object.defineProperty;var __name=(target,value)=>__defProp(target,"name",{value,configurable:true});import{pad}from"lodash";function sayHello(name){console.log(pad(`Hello ${name}`,80))}__name(sayHello,"sayHello");sayHello("World");
                                                                                                                         ^^^
SyntaxError: The requested module 'lodash' does not provide an export named 'pad'
    at ModuleJob._instantiate (https://nodebixnfe-doob.w-credentialless.staticblitz.com/blitz.09144545.js:181:1509)
    at async ModuleJob.run (https://nodebixnfe-doob.w-credentialless.staticblitz.com/blitz.09144545.js:181:2327)
```

Although there is also `lodash-es`, you still encounter packages importing `lodash` directly from within them, where replacing them all with `lodash-es` is difficult and sometimes causes issues, as those are sometimes meant to be consumed from vanilla Node.js CJS mode, which can't `require` ESM modules. And merging `lodash` into a proper hybrid package isn't happening anytime soon due to the poor maintenance status of lodash (https://github.com/lodash/lodash/issues/5107).

<img width="810" alt="screenshot" src="https://github.com/esbuild-kit/tsx/assets/24731903/390c1ba0-decb-447f-ac25-271dd1034387">

### Expected behavior

It just works.

### Minimal reproduction URL

https://stackblitz.com/edit/node-bixnfe?file=index.ts

### Version

v3.12.1

### Node.js version

v18.18.0

### Package manager

npm

### Operating system

Linux

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by pokey** [comment] 2023-11-06 16:34
Strangely, `esbuild` seems to work fine in this case. Ie I can do

```bash
esbuild input.ts --bundle --format=cjs --platform=node --outfile=output.cjs
node output.cjs
```

And it works fine. Any idea what tsx is doing differently such that we run into this issue?

**Comment by pokey** [comment] 2023-11-06 16:55
> Strangely, `esbuild` seems to work fine in this case. Ie I can do
> 
> ```shell
> esbuild input.ts --bundle --format=cjs --platform=node --outfile=output.cjs
> node output.cjs
> ```
> 
> And it works fine. Any idea what tsx is doing differently such that we run into this issue?

Sorry, any idea why the above comment was marked as spam?

**Comment by privatenumber** [comment] 2023-11-07 00:40
I hid it because Issues is for maintainers to triage and investigate bugs, and I prefer to keep the discussion productive towards finding a solution.

Your comment didn't particularly add anything. tsx is a different tool and with a different goal from esbuild, so I didn't see the relevance. And asking "why is this happening?" on an issue felt redundant as answering that is kind of the point of an issue.

Next time, please don't unhide a hidden comment by re-posting it. The point was to keep the thread clean.

**Comment by pokey** [comment] 2023-11-07 09:26
Apologies—I was so surprised that you would mark my comment as spam that I thought maybe I had done it myself by accident 😅

Fwiw, this issue strikes me as a duplicate of https://github.com/esbuild-kit/tsx/issues/38

Best of luck with your project

**Comment by privatenumber** [comment] 2023-12-05 15:03
Duplicate of https://github.com/privatenumber/tsx/issues/38

**Closed by privatenumber** 2023-12-05 15:03 UTC
Labels: bug, pending triage
