### ISSUE TITLE
Error loading JSON modules when required by dependencies

### ISSUE THREAD

**Issue by gcoonrod** [privatenumber/tsx#645] opened 2024-09-04 21:20 UTC
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/gcoonrod/tsx-error

### Problem & expected behavior (under 200 words)

Skip this section and let your reproduction do the talking...

But if you really need to explain, keep it under 200 words:
- What happened
- What I expected
- Error stack trace
- Documentation links
- Screenshots

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [X] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment] 2024-09-05 02:32
I think this is a duplicate of https://github.com/privatenumber/tsx/issues/640

**Comment by 9r1nc3w1ll** [comment] 2024-10-31 06:47
set "allowJs": false in your TS config.

**Comment by privatenumber** [comment] 2024-11-04 23:43
Closing as a duplicate

**Closed by privatenumber** 2024-11-04 23:43 UTC
Labels: bug, pending triage
