### ISSUE TITLE
tsx uses cwd instead of closest tsconfig.json

### ISSUE THREAD

**Issue by Zamiell** [privatenumber/tsx#362] opened 2023-10-31 13:45 UTC
### Problem

tsx won't use the correct "tsconfig.json" file, even if you put a "tsconfig.json" file right next to the script you are executing.

### Minimal reproduction URL

https://github.com/Zamiell/test

### Version

10.2.2

### Node.js version

v18.13.0

### Package manager

npm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment] 2023-11-01 00:24
When it comes to supporting multiple tsconfig files, I'll likely need to adjust the current behavior to utilize the closest tsconfig. However, I don't believe this approach is technically accurate.

The TypeScript Compiler relies on the `tsconfig.json` within the cwd for compilation configuration. This allows it to compile files that aren't even imported. However, in the case of tsx, the process is inverted, determining what to compile by traversing files from the entry point and generating a dependency tree.

Relying on the nearest `tsconfig.json` is an assumption that might not be suitable for every project. For instance, the closest tsconfig might have specific `includes` or `files` that don't cover that file, or it might have `excludes` that specifically exclude that file. e.g. How could we support a project that does `tsc -p tsconfig.test.json`?

**Comment by Zamiell** [comment] 2023-11-01 00:33
Hello privatenumber, and thanks for the quick reply!

I am sorry, I do understand that this ticket is nontrivial to fix. :(

I think `tsx` should try to parse the `include` and `exclude` field of the closest "tsconfig.json", and then try to move upwards in the directory tree until it finds a matching one.

But I think my reprex proves that the current behavior will make for a good number of frustrated users!

> How could we support a project that does tsc --project tsconfig.test.json?

In this case, I would argue that if they are invoking `tsc` with a specific "tsconfig.test.json", then they should also have to invoke `tsx` with a specific "tsconfig.test.json". If `tsx` is invoked with a specific "tsconfig.test.json", then maybe it can use the "compilerOptions" in that file and ignore the "include" and "exclude" field? Not sure.

**Comment by privatenumber** [comment] 2023-11-01 01:06
> In this case, I would argue that if they are invoking `tsc` with a specific "tsconfig.test.json", then they should also have to invoke `tsx` with a specific "tsconfig.test.json"

The problem is that there could be multiple tsconfig files applying to a dependency tree. For example, if there's a monorepo, where one package uses `tsconfig.json` but another packages uses `tsconig.test.json`, how can we detect that?

I might make it so tsx accepts multiple `--tsconfig` flags to create a map of possible tsconfigs to check if a nearest applying tsconfig isn't found.

**Comment by Zamiell** [comment] 2023-11-01 01:30
> The problem is that there could be multiple tsconfig files applying to a dependency tree. For example, if there's a monorepo, where one package uses tsconfig.json but another packages uses tsconig.test.json, how can we detect that?

To be clear of what you mean, I will make an example:

```text
project/
|── tsconfig.json
├── src/
|   └── main.ts
└── tests/
    ├── foo.test.ts
    └── tsconfig.test.json
```

- In this directory structure, the "foo.test.ts" file is meant to be paired with the "tsconfig.test.json" file.
- If we did `npx tsx foo.test.ts`, then in the current behavior of `tsx`, it would use the "tsconfig.json" file. (Bug)
- If we did `npx tsx foo.test.ts` using my proposed algorithm, then it would use the "tsconfig.json" file. (Bug)

It's also similar in this example (slightly modified):

```text
project/
|── tsconfig.json
|── tsconfig.test.json
├── src/
|   └── main.ts
└── tests/
    └── foo.test.ts
```

The problem in both of these examples is that `tsx` is looking for an exact match of "tsconfig.json". We could relax this and instead:

1) Look for "tsconfig.json" in the directory next to the file.
2) If include/export is a match, then done.
3) Otherwise, search for "tsconfig*.json in the directory next to the file.
4) If include/export is a match, then done.
5) Go up a directory and repeat from 1 until the root of the file system is reached.

> The problem is that there could be multiple tsconfig files applying to a dependency tree.

In projects with multiple "tsconfig.json", it is idiomatic to use the include/exclude fields to e.g. exclude test files and so on and so forth. Are you thinking that there will be an issue where a user will want a tsconfig in a deep parent directory to take precedence over a closer tsconfig? This seems very strange to me. I would be very surprised if anyone had a TypeScript monorepo set up this way, it is not a sane TypeScript setup in my opinion.

**Comment by privatenumber** [comment] 2023-11-01 01:47
> Otherwise, search for "tsconfig*.json in the directory next to the file.

This naming convention is also a big assumption. It can be named `asdf.json` and we should still be able to handle it.

Thoughts on my proposed solution?

**Comment by Zamiell** [comment] 2023-11-01 02:57
> This naming convention is also a big assumption. It can be named asdf.json and we should still be able to handle it.

I think it is a small assumption, not a big assumption. =p But okay, we could search for files in the following order:

- tsconfig.json
- tsconfig*.json
- *.json

For each file examined, we parse it using the tsconfig schema: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsconfig.json

If the file does not pass the schema, it is not valid, we skip it and look for other files. (Libraries like `Avj` can see if arbitrary JSON files pass schema.)

However, I don't think this is a very good solution, as maybe we get false positives. This is very weird behavior, unexpected, and difficult for end-users to troubleshoot, just to support very small percentage of users who name their tsconfig.json file super weird names! So I think we should not support it. For users that want to name their tsconfig very weird names, then it is reasonable for them to have to give `--tsconfig` option to `tsx`.

**Comment by privatenumber** [comment] 2023-11-01 04:47
lol That was a lot of writing just to say "I agree with the multiple `--tsconfig` proposal" 😅.

BTW If there's anything I learned about scale, small assumptions become big very fast. If you want to check 3 file paths per module, you'd be hitting the file-system over 300 times for a project with 100 files. This performance hit is exactly why ESM no longer allows implicit extensions in import paths.

That said, I won't be adding arbitrary "guess work" to the resolution algorithm (at least without precedent in a spec).

**Comment by privatenumber** [comment] 2023-11-09 10:07
Closing as a duplicate of https://github.com/privatenumber/tsx/issues/265

**Closed by privatenumber** 2023-11-09 10:07 UTC
Labels: bug, pending triage
