### ISSUE TITLE
`tsx watch` restarts when receiving console input

### ISSUE THREAD

**Issue by pMattheew** [privatenumber/tsx#456] opened 2024-01-16 16:35 UTC
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://stackblitz.com/edit/stackblitz-starters-r4bzwx?file=index.js

### Version

v4.7.0

### Node.js version

https://stackblitz.com/edit/stackblitz-starters-r4bzwx?file=index.js

### Package manager

npm

### Operating system

Linux

### Problem & Expected behavior

The first input is okay (although pressing Enter to send it also restarts the application), but the second and over causes the app to restart without even sending the input with Enter. 

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment] 2024-01-17 01:18
Duplicate of https://github.com/privatenumber/tsx/issues/163

**Closed by privatenumber** 2024-01-17 01:18 UTC
Labels: bug, pending triage
