### ISSUE TITLE
(pnpm) Using `tsx` in `postinstall` script generates unexpected file at `./tsx-0/`

### ISSUE THREAD

**Issue by NamesMT** [privatenumber/tsx#596] opened 2024-06-22 17:12 UTC
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Minimal reproduction URL

https://stackblitz.com/github/namesmt/repro-tsx

### Problem & expected behavior (under 200 words)

Alternative github repo because stackblitz could not load for me, idk if it's just me: https://github.com/NamesMT/repro-tsx

Simply run `pnpm install`, an unexpected file is created along with the folder `tsx-0`
![image](https://github.com/privatenumber/tsx/assets/23612546/f19ca78f-da0b-4378-8d1f-4ff72125268b)

It does not happen with normal `npm`

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment] 2024-06-22 21:08
I can't reproduce this on my end. Can you use GitHub Actions or something to demonstrate it?

**Comment by NamesMT** [comment] 2024-06-23 06:04
Hello @privatenumber,

Here is a oneline reproduction using docker run: `docker run -it --rm namesmt/images-alpine:node-dev zsh -c "cd home && nlx giget gh:namesmt/repro-tsx repro-tsx && cd repro-tsx && ni && ls && ls tsx-0 && zsh"`

![image](https://github.com/privatenumber/tsx/assets/23612546/4b3f68c4-85d1-480a-bc8c-9f1e1ba3a6a7)

**Comment by privatenumber** [comment] 2024-06-23 06:08
Sorry but a screenshot doesn't help.

I need a reproduction env for me to debug and test fixes in.

**Comment by NamesMT** [comment] 2024-06-23 09:00
Hello @privatenumber, idk why but for github's default runners in I could not reproduce it, but does indeed exists because I could reproduce the issue on my work machine which uses plain Ubuntu,

I have also do more tests and it is indeed reproducible on various docker images: `ubuntu`, `node`/`node:slim`, `alpine`.

I have also able to reproduce it on my company Gitlab CI with `node:alpine` image.

For your convenience, I have setup a repo in which I was able to use Github Actions to reproduce it (using docker container action): https://github.com/NamesMT/repro-tsx-action
You could simply fork it and push commits/PR to test.

Thanks a lot.

**Comment by privatenumber** [comment] 2024-06-23 09:09
I appreciate it, thanks @NamesMT 

I haven't confirmed this, but I believe this is actually https://github.com/pnpm/pnpm/issues/7330

[tsx creates a cache directory in `os.tmpdir()`](https://github.com/privatenumber/tsx/blob/98d9f6dc9edd8d6e182b8b1a854f585f678f22a1/src/utils/temporary-directory.ts#L22) which implies pnpm in Alpine is returning the current working directory in the [env variables](https://github.com/nodejs/node/blob/e0bbe8fd52bf64036f06153df338fcd1d2ca32a1/lib/os.js#L181).

Will take a closer look later on.

**Comment by NamesMT** [comment] 2024-06-23 09:37
That seems to be it, maybe we can apply a workaround like [`jiti#123`](https://github.com/unjs/jiti/pull/123)?

**Comment by privatenumber** [comment] 2024-06-23 22:36
If it's rooted in pnpm, then it's not a tsx bug. And I would rather not patch bugs from other tools via tsx.

This is for the same reasons I would relay any Node bugs we get to https://github.com/nodejs/node. Encouraging fixes to be made in the right places maximizes benefit to the community.

Can you verify this is what's causing it by running pnpm with [`unsafe-perm`](https://pnpm.io/npmrc#unsafe-perm)? https://github.com/pnpm/npm-lifecycle/blob/1e0f149176877f906968a01087cf63290652ccbc/index.js#L100
If so, try opening a PR there.

**Comment by NamesMT** [comment] 2024-06-24 04:00
Yes I can verify that running pnpm with `unsafe-perm`, the issue is not present, thanks a lot for finding the root cause.
Don't have time to open a PR yet but I'll do it when I do and no one has created one specific to it.

**Comment by privatenumber** [comment] 2024-06-29 00:58
Closing as it's a bug in pnpm rather than tsx

**Closed by privatenumber** 2024-06-29 00:58 UTC
Labels: bug
