### ISSUE TITLE
!!"" evaluates to undefined in the REPL

### ISSUE THREAD

**Issue by ninofiliu** [privatenumber/tsx#409] opened 2023-11-22 18:14 UTC
### Precheck

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I'm able to reproduce this issue and prove it with a minimal reproduction
- [X] I understand this is not a place to ask for free debugging support

### Problem

`!!""` evaluates to `false` but in the REPL it evaluates to `undefined`

### Expected behavior

It should evaluate to `false` like in the node REPL

What is weird is that I type `!!""` and it rightly suggests `false` in the response yet when I type enter this is overwritten to `undefined`

### Minimal reproduction URL

https://example.com

### Version

v4.3.0

### Node.js version

v18.8.0

### Package manager

pnpm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment] 2023-11-22 18:54
Duplicate of https://github.com/privatenumber/tsx/issues/327

**Closed by privatenumber** 2023-11-22 18:54 UTC
Labels: bug, pending triage
