### ISSUE TITLE
Incompatible with `import-in-the-middle` loader

### ISSUE THREAD

**Issue by timfish** [privatenumber/tsx#554] opened 2024-05-14 14:48 UTC
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I am reporting a confirmed bug (not seek debugging help)
- [X] I understand this is a collaborative project and relies on my contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/develop/CONTRIBUTING.md)

### Problem & expected behavior (under 200 words)

With `import-in-the-middle@1.7.1` and the following code

`test.ts`
```ts
import { register } from "node:module";
register("import-in-the-middle/hook.mjs", import.meta.url);
await import("node:util");
```

Running:
```
tsx test.ts
```

I get the following stack trace:
```
TypeError: The URL must be of scheme file
    at new NodeError (node:internal/errors:406:5)
    at fileURLToPath (node:internal/url:1393:11)
    at finalizeResolution (node:internal/modules/esm/resolve:234:42)
    at moduleResolve (node:internal/modules/esm/resolve:845:10)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at nextResolve (node:internal/modules/esm/hooks:833:28)
    at y (file:///Users/tim/Documents/Repositories/sentry-v8-tsx-error-repro/node_modules/tsx/dist/esm/index.mjs?1715697897382:128:19)
    at j (file:///Users/tim/Documents/Repositories/sentry-v8-tsx-error-repro/node_modules/tsx/dist/esm/index.mjs?1715697897382:191:20)
    at nextResolve (node:internal/modules/esm/hooks:833:28)
    at resolve (/Users/tim/Documents/Repositories/sentry-v8-tsx-error-repro/node_modules/import-in-the-middle/hook.js:94:23) 
```

If you disable `allowJs` this no longer errors.

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Supporting engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment] 2024-05-14 15:06
I'm going to close this temporarily for bug tracking purposes since the minimal reproduction should prove that the bug is in `tsx` rather than `import-in-the-middle`.

But don't let that deter you and feel free to investigate further. If you determine it's actually a bug in tsx, I'd be happy to accept a PR.

The published tsx code is minified, but the contribution guide has development tips on how you can turn it off and use the dev version:
https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md#development

**Closed by privatenumber** 2024-05-14 15:06 UTC
Labels: bug, pending triage

**Comment by timfish** [comment] 2024-05-14 18:19
Do you have any tips for debugging loader hooks? I'm `console.log`ing in multiple modules but it's super painful to not be able to add breakpoints in the node built in code!

**Comment by timfish** [comment] 2024-05-14 19:59
Turns out it's a Node issue caused by the fact that `import-in-the-middle` sets `parentURL` to `node:*`. This bug is only triggered when the file is not found which is triggered in `tsx` because it attempts to load missing files while searching for various extensions.

https://github.com/nodejs/node/issues/52987
