### ISSUE TITLE
`tsx` should have option to not do extra things

### ISSUE THREAD

**Issue by loynoir** [privatenumber/tsx#228] opened 2023-04-26 23:10 UTC
### Bug description

`tsx` should have option to not do extra things.

### Prepare
`reproduce1.mjs`

```ts
// @ts-check
import playwright from 'playwright-core'
const browser = await playwright.firefox.launch()
const browserContext = await browser.newContext()
const page = await browserContext.newPage()
await page.goto('http://127.0.0.1:1234/')
await page.waitForFunction('() => true')
await page.close()
await browserContext.close()
await browser.close()
```

```sh
$ cp reproduce1.mjs reproduce2.mts
```

### Actual
```
$ npm exec -- tsx reproduce1.mjs
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

page.waitForFunction: __name is not defined
@debugger eval code line 195 > eval:1:95
evaluate@debugger eval code:197:17
@debugger eval code:1:44

    at file:///path/to/reproduce1.mjs:7:12 {
  name: 'Error'
}

Node.js v18.15.0
```

```
$ npm exec -- tsx reproduce2.mts
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

page.waitForFunction: __name is not defined
@debugger eval code line 195 > eval:1:95
evaluate@debugger eval code:197:17
@debugger eval code:1:44

    at <anonymous> (/path/to/reproduce2.mts:7:12) {
  name: 'Error'
}

Node.js v18.15.0
```

### Expected

```sh
$  node --loader @esbuild-kit/esm-loader reproduce1.mjs && echo OK
(node:615388) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
OK
```

```sh
$ node --loader @esbuild-kit/esm-loader reproduce2.mts && echo OK
(node:615873) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
OK
```

### Environment

```shell
Binaries:
    Node: 18.15.0 - /usr/sbin/node
    Yarn: 1.22.19 - /usr/sbin/yarn
    npm: 8.19.2 - /usr/sbin/npm
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

### Related

https://github.com/esbuild-kit/tsx/issues/113

**Comment by privatenumber** [comment] 2023-04-26 23:26
> tsx should have option to not do extra things.

Not sure what you're talking about. Can you elaborate?

Seems like a duplicate of #113?

**Comment by loynoir** [comment] 2023-04-26 23:36
@privatenumber 

> Seems like a duplicate of https://github.com/esbuild-kit/tsx/issues/113?

No. 

https://github.com/esbuild-kit/esno/blob/v0.14.1/esmo.mjs

For example, `esmo@0.14.1` just means `node --loader esbuild-node-loader`.

`tsx` does not mean `node --loader @esbuild-kit/esm-loader`, they have different output.

`node --loader @esbuild-kit/esm-loader`  works fine. 

But `tsx` works unexpected.

**Comment by privatenumber** [comment] 2023-04-26 23:51
I see.

`node --loader @esbuild-kit/esm-loader` works for your input because `playwight-core` is a [CommonJS package](https://unpkg.com/playwright-core@1.32.3/index.js), and `@esbuild-kit/esm-loader` only transforms ESM files.

tsx does `node --loader @esbuild-kit/esm-loader --require @esbuild-kit/cjs-loader` which adds support for transforming CommonJS too (transforming playwright-core). But currently, it transforms more than it needs to (it doesn't need to transform playwright-core).

**Comment by saonan90077** [comment] 2023-05-26 01:36
mark

**Comment by FiggerDancer** [comment] 2023-07-27 15:03
same error here
mark

**Comment by privatenumber** [comment] 2023-11-09 08:15
`playwright-core` should work expectedly now with https://github.com/privatenumber/tsx/releases/tag/v4.0.0

Hope it works well for you!

**Closed by privatenumber** 2023-11-09 08:15 UTC
Labels: performance
