### ISSUE TITLE
ctrl-c (SIGINT) when launching via --inspect-brk and using dedicated DevTools for Node will not term process or debugger

### ISSUE THREAD

**Issue by midzelis** [privatenumber/tsx#252] opened 2023-06-09 16:14 UTC
### Bug description

Open Chrome Dedicated DevTools for Node
Run tsx --debug-inspect
Press ctrl-c, this does not terminate the process. 

If you run this via node directly, it will work as expected: Pressing ctrl-c will stop the program and disconnect it from Chrome DevTools. 

### Reproduction

1. Create a simple hello world app with a debugger
2. Open chrome://inspect and click "Open dedicated DevTools for Node" 
3. Run `tsx --debug-inspect hello.ts`
4. Chrome will auto start debugging
5. Press ctrl-c  - process will not terminate, but chrome debugger not active anymore

### Environment

```shell
tsx 3.12.7, chrome Version 114.0.5735.106 (Official Build) (x86_64), node v18.16.0
```

### Can you work on a fix?

- [ ] I’m interested in opening a pull request to address this issue.

**Comment by privatenumber** [comment] 2023-11-23 05:39
Just looked into this

1. `--debug-inspect` is not a valid flag.

2. Tried with `--inspect` and a file that contains `setTimeout(() => {}, 1e5)` and I could <kbd>Ctrl+C</kbd> just fine.

Closing as I can't reproduce this (maybe it was fixed recently? but I can't verify because not sure how to repro). Happy to reopen if you can provide a reproduction.

**Closed by privatenumber** 2023-11-23 05:39 UTC
Labels: bug, pending triage
