### ISSUE TITLE
Inspect with chrome as debugger result in ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by TzeroOcne** [privatenumber/tsx#661] opened 2024-10-04 08:34 UTC
### Acknowledgements

- [X] I read the documentation and searched existing issues to avoid duplicates
- [X] I understand this is a **bug tracker** and anything other than a proven bug will be closed
- [X] I understand this is a free project and relies on community contributions
- [X] I read and understood the [Contribution guide](https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md)

### Minimal reproduction URL

https://github.com/TzeroOcne/tsx-issue

### Problem & expected behavior (under 200 words)

- What happened
I try to run `tsx` with `--inspect` by `pnpm start:tsx`
- What I expected
I expect I can open debugger tool from browser and it will show the ts file that are beign debugged like the example when I use `ts-node`
- Error stack trace
The error that I got from the debugger are this
```
Could not load content for file:///C:/Users/tzero/temp/tsx-test/src/C:\Users\tzero\temp\tsx-test\src\index.ts (System error: net::ERR_FILE_NOT_FOUND)
```
- Documentation links
I don't think there is any documentation about inspect using chrome as debugger
- Screenshots
This what I expect by using ts-node by running `pnpm start:ts-node`
![image](https://github.com/user-attachments/assets/6889c3d1-6c43-43b3-9945-e5703ce20ae6)
But I got this with tsx by running `pnpm start:tsx`
![image](https://github.com/user-attachments/assets/1f458539-db5f-4e97-8b0a-d4c3515283d9)

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work will speed up resolution and support the project

- [ ] I'm willing to offer $10 for financial support

**Comment by privatenumber** [comment] 2024-10-13 15:50
Thanks for the issue. Feel free to work on a PR!

**Comment by char8x** [comment] 2024-10-23 09:58
I did some simple tests and found the difference on sourcemap

Take the following code as an example

```ts
// test.ts
setInterval(() => {
  debugger
  console.log("aaa");
}, 2000)
```

After executing the `tsx --inspect ./test.ts` command (tsx v4.19.1) , the sourcemap json is generated as follows

```json
{
  "version": 3,
  "mappings": "AAAA,YAAY,IAAM,CAChB,SACA,QAAQ,IAAI,KAAK,CACnB,EAAG,GAAI",
  "names": [],
  "ignoreList": [],
  "sources": [
    "/home/debian/tsx-vs-ts-node-inspect/test.ts"
  ],
  "sourcesContent": [
    null
  ]
}
```

After executing the `node --import ./ts-node-register.js --inspect ./test.ts` command (ts-node v10.9.2), the sourcemap json is generated as follows

```json
{
  "version": 3,
  "file": "/home/debian/tsx-vs-ts-node-inspect/test.ts",
  "sources": [
    "/home/debian/tsx-vs-ts-node-inspect/test.ts"
  ],
  "names": [],
  "mappings": "AAAA,WAAW,CAAC,GAAG,EAAE;IACf,QAAQ,CAAA;IACR,OAAO,CAAC,GAAG,CAAC,KAAK,CAAC,CAAC;AACrB,CAAC,EAAE,IAAI,CAAC,CAAA",
  "sourcesContent": [
    "setInterval(() => {\n  debugger\n  console.log(\"aaa\");\n}, 2000)\n"
  ]
}
```

I think the problem may be caused by the missing attributes of `file` or `sourcesContent` in the sourcemap json generated by tsx

**Comment by char8x** [comment] 2024-10-23 10:34
I've tweaked the tsx source code a little bit.

```diff
diff --git a/src/utils/transform/index.ts b/src/utils/transform/index.ts
index 8448df3..6e1b563 100644
--- a/src/utils/transform/index.ts
+++ b/src/utils/transform/index.ts
@@ -101,10 +101,14 @@ export const transform = async (
 ): Promise<Transformed> => {
        const esbuildOptions = {
                ...cacheConfig,
                format: 'esm',
                sourcefile: filePath,
+               // Reference
+               // https://github.com/evanw/esbuild/blob/d34e79e2a998c21bb71d57b92b0017ca11756912/lib/shared/types.ts#L16
+               // https://esbuild.github.io/api/#sources-content
+               sourcesContent: true,
                ...extendOptions,
        } as const;
 
        const hash = sha1([
                code,

```

After executing the `./dist/cli.mjs --inspect ./test.ts` command, the sourcemap json is generated as follows:

```json
{
  "version": 3,
  "mappings": "AAAA,YAAY,IAAM,CAChB,SACA,QAAQ,IAAI,KAAK,CACnB,EAAG,GAAI",
  "names": [],
  "ignoreList": [],
  "sources": [
    "/home/debian/projects/2024-daily/tsx-vs-ts-node-inspect/test2.ts"
  ],
  "sourcesContent": [
    "setInterval(() => {\n  debugger\n  console.log(\"aaa\");\n}, 2000)\n"
  ]
}
```

Then `debugger` in Chrome Dev Tools works.

<img width="379" alt="图片" src="https://github.com/user-attachments/assets/c032b745-f8da-4be6-b09c-d79d3a4db079">

While the problem is temporarily solved, the mechanics of how Chrome Dev Tools handles sourcemaps are still not particularly clear.

**Comment by privatenumber** [comment] 2024-10-23 18:54
Thanks for investigating.

Would you be interested in opening a PR to handle that condition here?
https://github.com/privatenumber/tsx/blob/315d5f44f301424de595873f93c102a5c184ab46/src/utils/transform/get-esbuild-options.ts#L24

If the CLI flag is the only way to check if Node is in debugger mode, you can do something like this to check if the flag is passed in:
https://github.com/privatenumber/tsx/blob/315d5f44f301424de595873f93c102a5c184ab46/src/run.ts#L36

**Comment by privatenumber** [comment] 2024-10-26 23:24
closed via https://github.com/privatenumber/tsx/pull/670

**Closed by privatenumber** 2024-10-26 23:24 UTC
Labels: bug, pending triage
